"""Initial models setup

Revision ID: 0cd474fcdb99
Revises: 
Create Date: 2025-06-26 17:03:12.761510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd474fcdb99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('filepath', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.Column('last_viewed_date', sa.DateTime(), nullable=True),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('engagement_level', sa.String(length=50), nullable=True),
    sa.Column('custom_note', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('user_summary', sa.Text(), nullable=True),
    sa.Column('ai_topic_label', sa.String(length=100), nullable=True),
    sa.Column('win_criteria_description', sa.Text(), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('actual_score', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('context_event', sa.String(length=200), nullable=True),
    sa.Column('is_goal_related', sa.Boolean(), nullable=False),
    sa.Column('filename_normalized', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('ultimate_goal', sa.Text(), nullable=True),
    sa.Column('role_model_character', sa.String(length=100), nullable=True),
    sa.Column('workspace_vibe', sa.String(length=100), nullable=True),
    sa.Column('workspace_color_theme', sa.String(length=50), nullable=True),
    sa.Column('selected_avatar', sa.String(length=100), nullable=True),
    sa.Column('short_term_mode_active', sa.Boolean(), nullable=True),
    sa.Column('short_term_mode_end_date', sa.Date(), nullable=True),
    sa.Column('short_term_mode_focus_keywords', sa.Text(), nullable=True),
    sa.Column('short_term_mode_intensity', sa.String(length=10), nullable=True),
    sa.Column('short_term_mode_last_used', sa.Date(), nullable=True),
    sa.Column('specific_study_goal', sa.Text(), nullable=True),
    sa.Column('preferred_content_types', sa.Text(), nullable=True),
    sa.Column('expected_completion_time', sa.String(length=50), nullable=True),
    sa.Column('personal_learning_challenges', sa.Text(), nullable=True),
    sa.Column('studyvault_expectations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('learning_objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('learning_role', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['learning_objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('user_content', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['workspace_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_item_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['workspace_item.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['workspace_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_item_relation')
    op.drop_table('workspace_item')
    op.drop_table('learning_objective')
    op.drop_table('user')
    op.drop_table('document')
    # ### end Alembic commands ###
