# Bên trong file migrations/versions/0f81a30667fa_....py

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0f81a30667fa' # Kiểm tra revision ID của bạn
down_revision = 'a4e5781a677c' # Kiểm tra revision trước đó của bạn
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.VARCHAR(length=20), nullable=False, server_default='file')) # <<< ĐẢM BẢO CÓ server_default='file' Ở ĐÂY

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('doc_type')

    # ### end Alembic commands ###