"""Add context_event to Document

Revision ID: 663dcaeb9c07
Revises: f194dfc74226
Create Date: 2025-06-09 13:23:47.478678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663dcaeb9c07'
down_revision = 'f194dfc74226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_event', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('context_event')

    # ### end Alembic commands ###
