"""Add all new features fields

Revision ID: 88d2c7b74974
Revises: 0f81a30667fa
Create Date: 2025-05-01 02:07:18.195322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d2c7b74974'
down_revision = '0f81a30667fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('context_event', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('custom_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_topic_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('ai_topic_label')
        batch_op.drop_column('user_summary')
        batch_op.drop_column('custom_note')
        batch_op.drop_column('context_event')
        batch_op.drop_column('engagement_level')

    # ### end Alembic commands ###
