"""Add learning_objective table

Revision ID: 915171931ef6
Revises: 663dcaeb9c07
Create Date: 2025-06-09 14:47:41.738897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915171931ef6'
down_revision = '663dcaeb9c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('learning_role', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['learning_objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('learning_goal')

    with op.batch_alter_table('workspace_item', schema=None) as batch_op:
        batch_op.drop_column('learning_role')
        batch_op.drop_column('importance')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('importance', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('learning_role', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_goal', sa.VARCHAR(length=200), nullable=True))

    op.drop_table('learning_objective')
    # ### end Alembic commands ###
