"""Initialize database without KeyResults

Revision ID: f194dfc74226
Revises: 
Create Date: 2025-06-09 13:03:48.904416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f194dfc74226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('filepath', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.Column('last_viewed_date', sa.DateTime(), nullable=True),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('engagement_level', sa.String(length=50), nullable=True),
    sa.Column('custom_note', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('learning_goal', sa.String(length=200), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('win_criteria_description', sa.Text(), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('actual_score', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('workspace_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('user_content', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('learning_role', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['workspace_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_item')
    op.drop_table('document')
    # ### end Alembic commands ###
